FROM node:20-alpine AS dev
WORKDIR /app

# Install dependencies
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

# Copy source code
COPY frontend ./

EXPOSE 5173

CMD ["npm", "run", "dev"]
